### PR TITLE
Table tooltips 

### PR DESCRIPTION
**Pull request by jgyou-bu**
Addresses #13. Adds tooltips that match spreadsheet template.

### CODE REVIEW

**Comment by jgyou-bu** [comment]
Replaces pull request #21 due to formatting/merge issues.

**Review by frederickjansen — COMMENTED** [review]
- Red tooltip is hard to read
- Sometimes tooltips won't go away and multiple ones are "stuck" on the screen
- Should we have a tooltip for every field, or just the ones with an error?
- sail_hot.js should work without jQuery (or qtip), let's add a check to make sure the library exists

**Comment by jgyou-bu** [comment]
The tooltip lag is still showing up after trying a few qtip parameter changes - the jQuery check and color change have been made though.

**Comment by jgyou-bu** [comment]
Tooltips appear on click, and only error tooltips are currently enabled.

**Comment by frederickjansen** [comment]
I cherry picked and squashed the commits minus the merge manually.

**Pull request closed without merging**
