### PR TITLE
Generic tables

### PR DESCRIPTION
**Pull request by lucyq**
DO NOT MERGE OR REVIEW!

### CODE REVIEW

**Comment by lucyq** [comment]
Closes #86 #85

**Comment by frederickjansen** [comment]
@lucyq Is this ready for review?

**Comment by lucyq** [comment]
Yes, this is ready for review

**Comment by lucyq** [comment]
Need to add unit tests to sbolTests.js file

**Comment by lucyq** [comment]
@frederickjansen everything is ready except for resizing. I will add that back over the weekend.

**Comment by lucyq** [comment]
TODO: resizing, spinner, linting

**Comment by lucyq** [comment]
Survey questions need proper CSS

**Comment by lucyq** [comment]
Should we just remove analystController?

**Comment by lucyq** [comment]
Ready for initial review so I can make any additional changes soon! @frederickjansen

**Comment by lucyq** [comment]
order of arrow is off

**Comment by lucyq** [comment]
need to put back CSV for survey questions

**Pull request closed without merging**
